# Generated by Django 6.0.3 on 2026-03-06 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_statistics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('school', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('time', models.CharField(help_text='ex: 2023, En cours, 2022 - 2023', max_length=255)),
                ('order', models.IntegerField(default=0, help_text='Order of display (0 = first)')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('time', models.CharField(help_text='ex: 2022 - Présent, 2023, —', max_length=255)),
                ('order', models.IntegerField(default=0, help_text='Order of display (0 = first)')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('percentage', models.IntegerField(default=50, help_text='Skill level from 0 to 100')),
                ('order', models.IntegerField(default=0, help_text='Order of display (0 = first)')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
